# Generated by Django 4.1.2 on 2022-12-22 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 11, 19, 49, 200293, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
